site_name: CTF Writeups by @jiegec
site_description: CTF Writeups by @jiegec
site_url: https://jia.je/ctf-writeups
copyright: Copyright &copy; 2025-2026 Jiajie Chen
nav:
  - Home: README.md
  - Writeups by Solution: misc/solution.md
  - Pyjail: misc/pyjail.md
  - Redbud Puppeteer: puppeteer/index.md
theme:
  custom_dir: overrides
  name: mkdocs
plugins:
  - glightbox
use_directory_urls: false
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
  analytics:
    provider: custom
